/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ILendingPoolAddressesProviderInterface
  extends ethers.utils.Interface {
  functions: {
    "getLendingPool()": FunctionFragment;
    "setLendingPoolImpl(address)": FunctionFragment;
    "getLendingPoolCore()": FunctionFragment;
    "setLendingPoolCoreImpl(address)": FunctionFragment;
    "getLendingPoolConfigurator()": FunctionFragment;
    "setLendingPoolConfiguratorImpl(address)": FunctionFragment;
    "getLendingPoolDataProvider()": FunctionFragment;
    "setLendingPoolDataProviderImpl(address)": FunctionFragment;
    "getLendingPoolParametersProvider()": FunctionFragment;
    "setLendingPoolParametersProviderImpl(address)": FunctionFragment;
    "getTokenDistributor()": FunctionFragment;
    "setTokenDistributor(address)": FunctionFragment;
    "getFeeProvider()": FunctionFragment;
    "setFeeProviderImpl(address)": FunctionFragment;
    "getLendingPoolLiquidationManager()": FunctionFragment;
    "setLendingPoolLiquidationManager(address)": FunctionFragment;
    "getLendingPoolManager()": FunctionFragment;
    "setLendingPoolManager(address)": FunctionFragment;
    "getPriceOracle()": FunctionFragment;
    "setPriceOracle(address)": FunctionFragment;
    "getLendingRateOracle()": FunctionFragment;
    "setLendingRateOracle(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getLendingPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingPoolImpl",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLendingPoolCore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingPoolCoreImpl",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLendingPoolConfigurator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingPoolConfiguratorImpl",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLendingPoolDataProvider",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingPoolDataProviderImpl",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLendingPoolParametersProvider",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingPoolParametersProviderImpl",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenDistributor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenDistributor",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeProvider",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeProviderImpl",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLendingPoolLiquidationManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingPoolLiquidationManager",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLendingPoolManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingPoolManager",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceOracle",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLendingRateOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingRateOracle",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getLendingPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingPoolImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLendingPoolCore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingPoolCoreImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLendingPoolConfigurator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingPoolConfiguratorImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLendingPoolDataProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingPoolDataProviderImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLendingPoolParametersProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingPoolParametersProviderImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeeProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeProviderImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLendingPoolLiquidationManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingPoolLiquidationManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLendingPoolManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingPoolManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLendingRateOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingRateOracle",
    data: BytesLike
  ): Result;

  events: {};
}

export class ILendingPoolAddressesProvider extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ILendingPoolAddressesProviderInterface;

  functions: {
    getLendingPool(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setLendingPoolImpl(
      _pool: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getLendingPoolCore(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setLendingPoolCoreImpl(
      _lendingPoolCore: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getLendingPoolConfigurator(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setLendingPoolConfiguratorImpl(
      _configurator: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getLendingPoolDataProvider(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setLendingPoolDataProviderImpl(
      _provider: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getLendingPoolParametersProvider(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setLendingPoolParametersProviderImpl(
      _parametersProvider: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getTokenDistributor(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setTokenDistributor(
      _tokenDistributor: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getFeeProvider(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setFeeProviderImpl(
      _feeProvider: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getLendingPoolLiquidationManager(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setLendingPoolLiquidationManager(
      _manager: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getLendingPoolManager(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setLendingPoolManager(
      _lendingPoolManager: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getPriceOracle(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setPriceOracle(
      _priceOracle: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getLendingRateOracle(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setLendingRateOracle(
      _lendingRateOracle: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  getLendingPool(overrides?: CallOverrides): Promise<string>;

  setLendingPoolImpl(
    _pool: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getLendingPoolCore(overrides?: CallOverrides): Promise<string>;

  setLendingPoolCoreImpl(
    _lendingPoolCore: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getLendingPoolConfigurator(overrides?: CallOverrides): Promise<string>;

  setLendingPoolConfiguratorImpl(
    _configurator: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getLendingPoolDataProvider(overrides?: CallOverrides): Promise<string>;

  setLendingPoolDataProviderImpl(
    _provider: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getLendingPoolParametersProvider(overrides?: CallOverrides): Promise<string>;

  setLendingPoolParametersProviderImpl(
    _parametersProvider: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getTokenDistributor(overrides?: CallOverrides): Promise<string>;

  setTokenDistributor(
    _tokenDistributor: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getFeeProvider(overrides?: CallOverrides): Promise<string>;

  setFeeProviderImpl(
    _feeProvider: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getLendingPoolLiquidationManager(overrides?: CallOverrides): Promise<string>;

  setLendingPoolLiquidationManager(
    _manager: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getLendingPoolManager(overrides?: CallOverrides): Promise<string>;

  setLendingPoolManager(
    _lendingPoolManager: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getPriceOracle(overrides?: CallOverrides): Promise<string>;

  setPriceOracle(
    _priceOracle: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getLendingRateOracle(overrides?: CallOverrides): Promise<string>;

  setLendingRateOracle(
    _lendingRateOracle: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    getLendingPool(overrides?: CallOverrides): Promise<string>;

    setLendingPoolImpl(_pool: string, overrides?: Overrides): Promise<void>;

    getLendingPoolCore(overrides?: CallOverrides): Promise<string>;

    setLendingPoolCoreImpl(
      _lendingPoolCore: string,
      overrides?: Overrides
    ): Promise<void>;

    getLendingPoolConfigurator(overrides?: CallOverrides): Promise<string>;

    setLendingPoolConfiguratorImpl(
      _configurator: string,
      overrides?: Overrides
    ): Promise<void>;

    getLendingPoolDataProvider(overrides?: CallOverrides): Promise<string>;

    setLendingPoolDataProviderImpl(
      _provider: string,
      overrides?: Overrides
    ): Promise<void>;

    getLendingPoolParametersProvider(
      overrides?: CallOverrides
    ): Promise<string>;

    setLendingPoolParametersProviderImpl(
      _parametersProvider: string,
      overrides?: Overrides
    ): Promise<void>;

    getTokenDistributor(overrides?: CallOverrides): Promise<string>;

    setTokenDistributor(
      _tokenDistributor: string,
      overrides?: Overrides
    ): Promise<void>;

    getFeeProvider(overrides?: CallOverrides): Promise<string>;

    setFeeProviderImpl(
      _feeProvider: string,
      overrides?: Overrides
    ): Promise<void>;

    getLendingPoolLiquidationManager(
      overrides?: CallOverrides
    ): Promise<string>;

    setLendingPoolLiquidationManager(
      _manager: string,
      overrides?: Overrides
    ): Promise<void>;

    getLendingPoolManager(overrides?: CallOverrides): Promise<string>;

    setLendingPoolManager(
      _lendingPoolManager: string,
      overrides?: Overrides
    ): Promise<void>;

    getPriceOracle(overrides?: CallOverrides): Promise<string>;

    setPriceOracle(_priceOracle: string, overrides?: Overrides): Promise<void>;

    getLendingRateOracle(overrides?: CallOverrides): Promise<string>;

    setLendingRateOracle(
      _lendingRateOracle: string,
      overrides?: Overrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getLendingPool(): Promise<BigNumber>;
    setLendingPoolImpl(_pool: string): Promise<BigNumber>;
    getLendingPoolCore(): Promise<BigNumber>;
    setLendingPoolCoreImpl(_lendingPoolCore: string): Promise<BigNumber>;
    getLendingPoolConfigurator(): Promise<BigNumber>;
    setLendingPoolConfiguratorImpl(_configurator: string): Promise<BigNumber>;
    getLendingPoolDataProvider(): Promise<BigNumber>;
    setLendingPoolDataProviderImpl(_provider: string): Promise<BigNumber>;
    getLendingPoolParametersProvider(): Promise<BigNumber>;
    setLendingPoolParametersProviderImpl(
      _parametersProvider: string
    ): Promise<BigNumber>;
    getTokenDistributor(): Promise<BigNumber>;
    setTokenDistributor(_tokenDistributor: string): Promise<BigNumber>;
    getFeeProvider(): Promise<BigNumber>;
    setFeeProviderImpl(_feeProvider: string): Promise<BigNumber>;
    getLendingPoolLiquidationManager(): Promise<BigNumber>;
    setLendingPoolLiquidationManager(_manager: string): Promise<BigNumber>;
    getLendingPoolManager(): Promise<BigNumber>;
    setLendingPoolManager(_lendingPoolManager: string): Promise<BigNumber>;
    getPriceOracle(): Promise<BigNumber>;
    setPriceOracle(_priceOracle: string): Promise<BigNumber>;
    getLendingRateOracle(): Promise<BigNumber>;
    setLendingRateOracle(_lendingRateOracle: string): Promise<BigNumber>;
  };

  populateTransaction: {
    getLendingPool(): Promise<PopulatedTransaction>;
    setLendingPoolImpl(_pool: string): Promise<PopulatedTransaction>;
    getLendingPoolCore(): Promise<PopulatedTransaction>;
    setLendingPoolCoreImpl(
      _lendingPoolCore: string
    ): Promise<PopulatedTransaction>;
    getLendingPoolConfigurator(): Promise<PopulatedTransaction>;
    setLendingPoolConfiguratorImpl(
      _configurator: string
    ): Promise<PopulatedTransaction>;
    getLendingPoolDataProvider(): Promise<PopulatedTransaction>;
    setLendingPoolDataProviderImpl(
      _provider: string
    ): Promise<PopulatedTransaction>;
    getLendingPoolParametersProvider(): Promise<PopulatedTransaction>;
    setLendingPoolParametersProviderImpl(
      _parametersProvider: string
    ): Promise<PopulatedTransaction>;
    getTokenDistributor(): Promise<PopulatedTransaction>;
    setTokenDistributor(
      _tokenDistributor: string
    ): Promise<PopulatedTransaction>;
    getFeeProvider(): Promise<PopulatedTransaction>;
    setFeeProviderImpl(_feeProvider: string): Promise<PopulatedTransaction>;
    getLendingPoolLiquidationManager(): Promise<PopulatedTransaction>;
    setLendingPoolLiquidationManager(
      _manager: string
    ): Promise<PopulatedTransaction>;
    getLendingPoolManager(): Promise<PopulatedTransaction>;
    setLendingPoolManager(
      _lendingPoolManager: string
    ): Promise<PopulatedTransaction>;
    getPriceOracle(): Promise<PopulatedTransaction>;
    setPriceOracle(_priceOracle: string): Promise<PopulatedTransaction>;
    getLendingRateOracle(): Promise<PopulatedTransaction>;
    setLendingRateOracle(
      _lendingRateOracle: string
    ): Promise<PopulatedTransaction>;
  };
}
