/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IFeeProviderContract
  extends Truffle.Contract<IFeeProviderInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<IFeeProviderInstance>;
}

type AllEvents = never;

export interface IFeeProviderInstance extends Truffle.ContractInstance {
  calculateLoanOriginationFee(
    _user: string,
    _amount: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  getLoanOriginationFeePercentage(
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  methods: {
    calculateLoanOriginationFee(
      _user: string,
      _amount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    getLoanOriginationFeePercentage(
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
