/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { AddressStorageContract } from "./AddressStorage";
import { AdminUpgradeabilityProxyContract } from "./AdminUpgradeabilityProxy";
import { ATokenContract } from "./AToken";
import { BaseAdminUpgradeabilityProxyContract } from "./BaseAdminUpgradeabilityProxy";
import { BaseUpgradeabilityProxyContract } from "./BaseUpgradeabilityProxy";
import { ChainlinkProxyPriceProviderContract } from "./ChainlinkProxyPriceProvider";
import { ContextContract } from "./Context";
import { DefaultReserveInterestRateStrategyContract } from "./DefaultReserveInterestRateStrategy";
import { Erc20Contract } from "./Erc20";
import { Erc20BurnableContract } from "./Erc20Burnable";
import { Erc20DetailedContract } from "./Erc20Detailed";
import { FeeProviderContract } from "./FeeProvider";
import { FlashLoanReceiverBaseContract } from "./FlashLoanReceiverBase";
import { GenericOracleIContract } from "./GenericOracleI";
import { IChainlinkAggregatorContract } from "./IChainlinkAggregator";
import { Ierc20Contract } from "./Ierc20";
import { Ierc20DetailedBytesContract } from "./Ierc20DetailedBytes";
import { IFeeProviderContract } from "./IFeeProvider";
import { IFlashLoanReceiverContract } from "./IFlashLoanReceiver";
import { IKyberNetworkProxyInterfaceContract } from "./IKyberNetworkProxyInterface";
import { ILendingPoolAddressesProviderContract } from "./ILendingPoolAddressesProvider";
import { ILendingRateOracleContract } from "./ILendingRateOracle";
import { InitializableAdminUpgradeabilityProxyContract } from "./InitializableAdminUpgradeabilityProxy";
import { InitializableUpgradeabilityProxyContract } from "./InitializableUpgradeabilityProxy";
import { IPriceOracleContract } from "./IPriceOracle";
import { IPriceOracleGetterContract } from "./IPriceOracleGetter";
import { IReserveInterestRateStrategyContract } from "./IReserveInterestRateStrategy";
import { LendingPoolContract } from "./LendingPool";
import { LendingPoolAddressesProviderContract } from "./LendingPoolAddressesProvider";
import { LendingPoolConfiguratorContract } from "./LendingPoolConfigurator";
import { LendingPoolCoreContract } from "./LendingPoolCore";
import { LendingPoolDataProviderContract } from "./LendingPoolDataProvider";
import { LendingPoolLiquidationManagerContract } from "./LendingPoolLiquidationManager";
import { LendingPoolParametersProviderContract } from "./LendingPoolParametersProvider";
import { LendingRateOracleContract } from "./LendingRateOracle";
import { MintableErc20Contract } from "./MintableErc20";
import { MockAggregatorBaseContract } from "./MockAggregatorBase";
import { MockAggregatorBatContract } from "./MockAggregatorBat";
import { MockAggregatorDaiContract } from "./MockAggregatorDai";
import { MockAggregatorKncContract } from "./MockAggregatorKnc";
import { MockAggregatorLendContract } from "./MockAggregatorLend";
import { MockAggregatorLinkContract } from "./MockAggregatorLink";
import { MockAggregatorManaContract } from "./MockAggregatorMana";
import { MockAggregatorMkrContract } from "./MockAggregatorMkr";
import { MockAggregatorRepContract } from "./MockAggregatorRep";
import { MockAggregatorSusdContract } from "./MockAggregatorSusd";
import { MockAggregatorTusdContract } from "./MockAggregatorTusd";
import { MockAggregatorUsdcContract } from "./MockAggregatorUsdc";
import { MockAggregatorUsdtContract } from "./MockAggregatorUsdt";
import { MockAggregatorWbtcContract } from "./MockAggregatorWbtc";
import { MockAggregatorZrxContract } from "./MockAggregatorZrx";
import { MockBatContract } from "./MockBat";
import { MockDaiContract } from "./MockDai";
import { MockFlashLoanReceiverContract } from "./MockFlashLoanReceiver";
import { MockKncContract } from "./MockKnc";
import { MockLendContract } from "./MockLend";
import { MockLendingPoolCoreContract } from "./MockLendingPoolCore";
import { MockLinkContract } from "./MockLink";
import { MockManaContract } from "./MockMana";
import { MockMkrContract } from "./MockMkr";
import { MockRepContract } from "./MockRep";
import { MockSusdContract } from "./MockSusd";
import { MockTusdContract } from "./MockTusd";
import { MockUsdcContract } from "./MockUsdc";
import { MockUsdtContract } from "./MockUsdt";
import { MockWbtcContract } from "./MockWbtc";
import { MockZrxContract } from "./MockZrx";
import { OwnableContract } from "./Ownable";
import { PriceOracleContract } from "./PriceOracle";
import { ProxyContract } from "./Proxy";
import { ReentrancyGuardContract } from "./ReentrancyGuard";
import { TokenDistributorContract } from "./TokenDistributor";
import { UintStorageContract } from "./UintStorage";
import { UpgradeabilityProxyContract } from "./UpgradeabilityProxy";
import { WalletBalanceProviderContract } from "./WalletBalanceProvider";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AddressStorage"): AddressStorageContract;
      require(
        name: "AdminUpgradeabilityProxy"
      ): AdminUpgradeabilityProxyContract;
      require(name: "AToken"): ATokenContract;
      require(
        name: "BaseAdminUpgradeabilityProxy"
      ): BaseAdminUpgradeabilityProxyContract;
      require(name: "BaseUpgradeabilityProxy"): BaseUpgradeabilityProxyContract;
      require(
        name: "ChainlinkProxyPriceProvider"
      ): ChainlinkProxyPriceProviderContract;
      require(name: "Context"): ContextContract;
      require(
        name: "DefaultReserveInterestRateStrategy"
      ): DefaultReserveInterestRateStrategyContract;
      require(name: "ERC20"): Erc20Contract;
      require(name: "ERC20Burnable"): Erc20BurnableContract;
      require(name: "ERC20Detailed"): Erc20DetailedContract;
      require(name: "FeeProvider"): FeeProviderContract;
      require(name: "FlashLoanReceiverBase"): FlashLoanReceiverBaseContract;
      require(name: "GenericOracleI"): GenericOracleIContract;
      require(name: "IChainlinkAggregator"): IChainlinkAggregatorContract;
      require(name: "IERC20"): Ierc20Contract;
      require(name: "IERC20DetailedBytes"): Ierc20DetailedBytesContract;
      require(name: "IFeeProvider"): IFeeProviderContract;
      require(name: "IFlashLoanReceiver"): IFlashLoanReceiverContract;
      require(
        name: "IKyberNetworkProxyInterface"
      ): IKyberNetworkProxyInterfaceContract;
      require(
        name: "ILendingPoolAddressesProvider"
      ): ILendingPoolAddressesProviderContract;
      require(name: "ILendingRateOracle"): ILendingRateOracleContract;
      require(
        name: "InitializableAdminUpgradeabilityProxy"
      ): InitializableAdminUpgradeabilityProxyContract;
      require(
        name: "InitializableUpgradeabilityProxy"
      ): InitializableUpgradeabilityProxyContract;
      require(name: "IPriceOracle"): IPriceOracleContract;
      require(name: "IPriceOracleGetter"): IPriceOracleGetterContract;
      require(
        name: "IReserveInterestRateStrategy"
      ): IReserveInterestRateStrategyContract;
      require(name: "LendingPool"): LendingPoolContract;
      require(
        name: "LendingPoolAddressesProvider"
      ): LendingPoolAddressesProviderContract;
      require(name: "LendingPoolConfigurator"): LendingPoolConfiguratorContract;
      require(name: "LendingPoolCore"): LendingPoolCoreContract;
      require(name: "LendingPoolDataProvider"): LendingPoolDataProviderContract;
      require(
        name: "LendingPoolLiquidationManager"
      ): LendingPoolLiquidationManagerContract;
      require(
        name: "LendingPoolParametersProvider"
      ): LendingPoolParametersProviderContract;
      require(name: "LendingRateOracle"): LendingRateOracleContract;
      require(name: "MintableERC20"): MintableErc20Contract;
      require(name: "MockAggregatorBase"): MockAggregatorBaseContract;
      require(name: "MockAggregatorBAT"): MockAggregatorBatContract;
      require(name: "MockAggregatorDAI"): MockAggregatorDaiContract;
      require(name: "MockAggregatorKNC"): MockAggregatorKncContract;
      require(name: "MockAggregatorLEND"): MockAggregatorLendContract;
      require(name: "MockAggregatorLINK"): MockAggregatorLinkContract;
      require(name: "MockAggregatorMANA"): MockAggregatorManaContract;
      require(name: "MockAggregatorMKR"): MockAggregatorMkrContract;
      require(name: "MockAggregatorREP"): MockAggregatorRepContract;
      require(name: "MockAggregatorSUSD"): MockAggregatorSusdContract;
      require(name: "MockAggregatorTUSD"): MockAggregatorTusdContract;
      require(name: "MockAggregatorUSDC"): MockAggregatorUsdcContract;
      require(name: "MockAggregatorUSDT"): MockAggregatorUsdtContract;
      require(name: "MockAggregatorWBTC"): MockAggregatorWbtcContract;
      require(name: "MockAggregatorZRX"): MockAggregatorZrxContract;
      require(name: "MockBAT"): MockBatContract;
      require(name: "MockDAI"): MockDaiContract;
      require(name: "MockFlashLoanReceiver"): MockFlashLoanReceiverContract;
      require(name: "MockKNC"): MockKncContract;
      require(name: "MockLEND"): MockLendContract;
      require(name: "MockLendingPoolCore"): MockLendingPoolCoreContract;
      require(name: "MockLINK"): MockLinkContract;
      require(name: "MockMANA"): MockManaContract;
      require(name: "MockMKR"): MockMkrContract;
      require(name: "MockREP"): MockRepContract;
      require(name: "MockSUSD"): MockSusdContract;
      require(name: "MockTUSD"): MockTusdContract;
      require(name: "MockUSDC"): MockUsdcContract;
      require(name: "MockUSDT"): MockUsdtContract;
      require(name: "MockWBTC"): MockWbtcContract;
      require(name: "MockZRX"): MockZrxContract;
      require(name: "Ownable"): OwnableContract;
      require(name: "PriceOracle"): PriceOracleContract;
      require(name: "Proxy"): ProxyContract;
      require(name: "ReentrancyGuard"): ReentrancyGuardContract;
      require(name: "TokenDistributor"): TokenDistributorContract;
      require(name: "UintStorage"): UintStorageContract;
      require(name: "UpgradeabilityProxy"): UpgradeabilityProxyContract;
      require(name: "WalletBalanceProvider"): WalletBalanceProviderContract;
    }
  }
}

export {
  AddressStorageContract,
  AddressStorageInstance
} from "./AddressStorage";
export {
  AdminUpgradeabilityProxyContract,
  AdminUpgradeabilityProxyInstance
} from "./AdminUpgradeabilityProxy";
export { ATokenContract, ATokenInstance } from "./AToken";
export {
  BaseAdminUpgradeabilityProxyContract,
  BaseAdminUpgradeabilityProxyInstance
} from "./BaseAdminUpgradeabilityProxy";
export {
  BaseUpgradeabilityProxyContract,
  BaseUpgradeabilityProxyInstance
} from "./BaseUpgradeabilityProxy";
export {
  ChainlinkProxyPriceProviderContract,
  ChainlinkProxyPriceProviderInstance
} from "./ChainlinkProxyPriceProvider";
export { ContextContract, ContextInstance } from "./Context";
export {
  DefaultReserveInterestRateStrategyContract,
  DefaultReserveInterestRateStrategyInstance
} from "./DefaultReserveInterestRateStrategy";
export { Erc20Contract, Erc20Instance } from "./Erc20";
export { Erc20BurnableContract, Erc20BurnableInstance } from "./Erc20Burnable";
export { Erc20DetailedContract, Erc20DetailedInstance } from "./Erc20Detailed";
export { FeeProviderContract, FeeProviderInstance } from "./FeeProvider";
export {
  FlashLoanReceiverBaseContract,
  FlashLoanReceiverBaseInstance
} from "./FlashLoanReceiverBase";
export {
  GenericOracleIContract,
  GenericOracleIInstance
} from "./GenericOracleI";
export {
  IChainlinkAggregatorContract,
  IChainlinkAggregatorInstance
} from "./IChainlinkAggregator";
export { Ierc20Contract, Ierc20Instance } from "./Ierc20";
export {
  Ierc20DetailedBytesContract,
  Ierc20DetailedBytesInstance
} from "./Ierc20DetailedBytes";
export { IFeeProviderContract, IFeeProviderInstance } from "./IFeeProvider";
export {
  IFlashLoanReceiverContract,
  IFlashLoanReceiverInstance
} from "./IFlashLoanReceiver";
export {
  IKyberNetworkProxyInterfaceContract,
  IKyberNetworkProxyInterfaceInstance
} from "./IKyberNetworkProxyInterface";
export {
  ILendingPoolAddressesProviderContract,
  ILendingPoolAddressesProviderInstance
} from "./ILendingPoolAddressesProvider";
export {
  ILendingRateOracleContract,
  ILendingRateOracleInstance
} from "./ILendingRateOracle";
export {
  InitializableAdminUpgradeabilityProxyContract,
  InitializableAdminUpgradeabilityProxyInstance
} from "./InitializableAdminUpgradeabilityProxy";
export {
  InitializableUpgradeabilityProxyContract,
  InitializableUpgradeabilityProxyInstance
} from "./InitializableUpgradeabilityProxy";
export { IPriceOracleContract, IPriceOracleInstance } from "./IPriceOracle";
export {
  IPriceOracleGetterContract,
  IPriceOracleGetterInstance
} from "./IPriceOracleGetter";
export {
  IReserveInterestRateStrategyContract,
  IReserveInterestRateStrategyInstance
} from "./IReserveInterestRateStrategy";
export { LendingPoolContract, LendingPoolInstance } from "./LendingPool";
export {
  LendingPoolAddressesProviderContract,
  LendingPoolAddressesProviderInstance
} from "./LendingPoolAddressesProvider";
export {
  LendingPoolConfiguratorContract,
  LendingPoolConfiguratorInstance
} from "./LendingPoolConfigurator";
export {
  LendingPoolCoreContract,
  LendingPoolCoreInstance
} from "./LendingPoolCore";
export {
  LendingPoolDataProviderContract,
  LendingPoolDataProviderInstance
} from "./LendingPoolDataProvider";
export {
  LendingPoolLiquidationManagerContract,
  LendingPoolLiquidationManagerInstance
} from "./LendingPoolLiquidationManager";
export {
  LendingPoolParametersProviderContract,
  LendingPoolParametersProviderInstance
} from "./LendingPoolParametersProvider";
export {
  LendingRateOracleContract,
  LendingRateOracleInstance
} from "./LendingRateOracle";
export { MintableErc20Contract, MintableErc20Instance } from "./MintableErc20";
export {
  MockAggregatorBaseContract,
  MockAggregatorBaseInstance
} from "./MockAggregatorBase";
export {
  MockAggregatorBatContract,
  MockAggregatorBatInstance
} from "./MockAggregatorBat";
export {
  MockAggregatorDaiContract,
  MockAggregatorDaiInstance
} from "./MockAggregatorDai";
export {
  MockAggregatorKncContract,
  MockAggregatorKncInstance
} from "./MockAggregatorKnc";
export {
  MockAggregatorLendContract,
  MockAggregatorLendInstance
} from "./MockAggregatorLend";
export {
  MockAggregatorLinkContract,
  MockAggregatorLinkInstance
} from "./MockAggregatorLink";
export {
  MockAggregatorManaContract,
  MockAggregatorManaInstance
} from "./MockAggregatorMana";
export {
  MockAggregatorMkrContract,
  MockAggregatorMkrInstance
} from "./MockAggregatorMkr";
export {
  MockAggregatorRepContract,
  MockAggregatorRepInstance
} from "./MockAggregatorRep";
export {
  MockAggregatorSusdContract,
  MockAggregatorSusdInstance
} from "./MockAggregatorSusd";
export {
  MockAggregatorTusdContract,
  MockAggregatorTusdInstance
} from "./MockAggregatorTusd";
export {
  MockAggregatorUsdcContract,
  MockAggregatorUsdcInstance
} from "./MockAggregatorUsdc";
export {
  MockAggregatorUsdtContract,
  MockAggregatorUsdtInstance
} from "./MockAggregatorUsdt";
export {
  MockAggregatorWbtcContract,
  MockAggregatorWbtcInstance
} from "./MockAggregatorWbtc";
export {
  MockAggregatorZrxContract,
  MockAggregatorZrxInstance
} from "./MockAggregatorZrx";
export { MockBatContract, MockBatInstance } from "./MockBat";
export { MockDaiContract, MockDaiInstance } from "./MockDai";
export {
  MockFlashLoanReceiverContract,
  MockFlashLoanReceiverInstance
} from "./MockFlashLoanReceiver";
export { MockKncContract, MockKncInstance } from "./MockKnc";
export { MockLendContract, MockLendInstance } from "./MockLend";
export {
  MockLendingPoolCoreContract,
  MockLendingPoolCoreInstance
} from "./MockLendingPoolCore";
export { MockLinkContract, MockLinkInstance } from "./MockLink";
export { MockManaContract, MockManaInstance } from "./MockMana";
export { MockMkrContract, MockMkrInstance } from "./MockMkr";
export { MockRepContract, MockRepInstance } from "./MockRep";
export { MockSusdContract, MockSusdInstance } from "./MockSusd";
export { MockTusdContract, MockTusdInstance } from "./MockTusd";
export { MockUsdcContract, MockUsdcInstance } from "./MockUsdc";
export { MockUsdtContract, MockUsdtInstance } from "./MockUsdt";
export { MockWbtcContract, MockWbtcInstance } from "./MockWbtc";
export { MockZrxContract, MockZrxInstance } from "./MockZrx";
export { OwnableContract, OwnableInstance } from "./Ownable";
export { PriceOracleContract, PriceOracleInstance } from "./PriceOracle";
export { ProxyContract, ProxyInstance } from "./Proxy";
export {
  ReentrancyGuardContract,
  ReentrancyGuardInstance
} from "./ReentrancyGuard";
export {
  TokenDistributorContract,
  TokenDistributorInstance
} from "./TokenDistributor";
export { UintStorageContract, UintStorageInstance } from "./UintStorage";
export {
  UpgradeabilityProxyContract,
  UpgradeabilityProxyInstance
} from "./UpgradeabilityProxy";
export {
  WalletBalanceProviderContract,
  WalletBalanceProviderInstance
} from "./WalletBalanceProvider";
