/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface UintStorageContract
  extends Truffle.Contract<UintStorageInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<UintStorageInstance>;
}

type AllEvents = never;

export interface UintStorageInstance extends Truffle.ContractInstance {
  getUint(_key: string, txDetails?: Truffle.TransactionDetails): Promise<BN>;

  methods: {
    getUint(_key: string, txDetails?: Truffle.TransactionDetails): Promise<BN>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
